
name: Auto-approve
on:
  pull_request:
    types: [ labeled ]

jobs:
  approve:
    if: ${{ github.event.label.name == 'dependencies' }}
    runs-on: ubuntu-latest
    env:
          GITHUB_TOKEN: ${{ secrets.AUTO_APPROVE_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.event.repository.name }}
    steps:
      - uses: nick96/auto-bors-dependabot-action@master
